// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/webhooks/app/scopes_update": {
    params: {};
  };
  "/webhooks/app/uninstalled": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/healthz": {
    params: {};
  };
  "/auth/*": {
    params: {
      "*": string;
    };
  };
  "/app": {
    params: {};
  };
  "/app/reindex": {
    params: {};
  };
  "/app/import": {
    params: {};
  };
  "/app/sync": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/webhooks/app/scopes_update" | "/webhooks/app/uninstalled" | "/auth/login" | "/healthz" | "/auth/*" | "/app" | "/app/reindex" | "/app/import" | "/app/sync";
  };
  "routes/webhooks.app.scopes_update.ts": {
    id: "routes/webhooks.app.scopes_update";
    page: "/webhooks/app/scopes_update";
  };
  "routes/webhooks.app.uninstalled.ts": {
    id: "routes/webhooks.app.uninstalled";
    page: "/webhooks/app/uninstalled";
  };
  "routes/auth.login.tsx": {
    id: "routes/auth.login";
    page: "/auth/login";
  };
  "routes/healthz.ts": {
    id: "routes/healthz";
    page: "/healthz";
  };
  "routes/auth.$.tsx": {
    id: "routes/auth.$";
    page: "/auth/*";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/app.tsx": {
    id: "routes/app";
    page: "/app" | "/app/reindex" | "/app/import" | "/app/sync";
  };
  "routes/app.reindex.tsx": {
    id: "routes/app.reindex";
    page: "/app/reindex";
  };
  "routes/app.import.tsx": {
    id: "routes/app.import";
    page: "/app/import";
  };
  "routes/app._index.tsx": {
    id: "routes/app._index";
    page: "/app";
  };
  "routes/app.sync.tsx": {
    id: "routes/app.sync";
    page: "/app/sync";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/webhooks.app.scopes_update": typeof import("./app/routes/webhooks.app.scopes_update.ts");
  "routes/webhooks.app.uninstalled": typeof import("./app/routes/webhooks.app.uninstalled.ts");
  "routes/auth.login": typeof import("./app/routes/auth.login.tsx");
  "routes/healthz": typeof import("./app/routes/healthz.ts");
  "routes/auth.$": typeof import("./app/routes/auth.$.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/app": typeof import("./app/routes/app.tsx");
  "routes/app.reindex": typeof import("./app/routes/app.reindex.tsx");
  "routes/app.import": typeof import("./app/routes/app.import.tsx");
  "routes/app._index": typeof import("./app/routes/app._index.tsx");
  "routes/app.sync": typeof import("./app/routes/app.sync.tsx");
};