client_id = "6aebdeb1f6abf29f3e80369a0811d47d"
name = "Marketing Copilot"
handle = "marketing-copilot-htn26"
application_url = "https://localhost:3458"
embedded = true

[build]
automatically_update_urls_on_dev = true

[access_scopes]
scopes = "read_products,write_products"

[auth]
redirect_urls = ["https://localhost:3458/auth/callback"]

[webhooks]
api_version = "2025-10"

  [[webhooks.subscriptions]]
  topics = ["app/uninstalled"]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = ["app/scopes_update"]
  uri = "/webhooks/app/scopes_update"
